url: https://github.com/longhorn/charts.git
subdirectory: charts/longhorn
commit: 93f250e4a175044d34c6982ea6168b213caeee9f
packageVersion: 00
releaseCandidateVersion: 00
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
